nyc_taxi:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/dbt/local.duckdb
      threads: 4
      extensions:
        - httpfs
        - parquet
      secrets:
        - type: s3
          region: "{{ env_var('S3_AWS_REGION') }}"
          key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"